expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from . import views  # Make sure views.py is in the same directory as urls.py


app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

myapp/models.py
from django.db import models

# Create your models here.

class Expense(models.Model):
    name = models.CharField(max_length=100)
    amount = models.IntegerField()
    category = models.CharField(max_length=50)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

myapp/forms.py
from django.forms import ModelForm
from .models import Expense


class ExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = ['name','amount','category']

myapp/views.py
from django.shortcuts import redirect, render
from .forms import ExpenseForm  # Corrected import statement
from .models import Expense
import datetime
from django.db.models import Sum


def index(request):
    if request.method == "POST":
        expense_form = ExpenseForm(request.POST)
        if expense_form.is_valid():
            expense_form.save()
    
    
    expenses = Expense.objects.all()
    total_expenses = expenses.aggregate(total_amount=Sum('amount'))
    
    #logic to calculate 365 days expenses
    last_year = datetime.date.today() - datetime.timedelta(days=365)
    data = Expense.objects.filter(date__gt=last_year)
    yearly_sum = data.aggregate(total_amount=Sum('amount'))

    #logic to calculate 30 days expenses
    last_months = datetime.date.today() - datetime.timedelta(days=30)
    data = Expense.objects.filter(date__gt=last_months)
    monthly_sum = data.aggregate(total_amount=Sum('amount'))

    #logic to calculate 7 days expenses
    week_months = datetime.date.today() - datetime.timedelta(days=30)
    data = Expense.objects.filter(date__gt=week_months)
    week_sum = data.aggregate(total_amount=Sum('amount'))

    #logic to calculate daily expenses
    daily_sums = Expense.objects.filter().values('date').order_by('date').annotate(sum=Sum('amount'))

    print(daily_sums)

    category_sums = Expense.objects.filter().values('category').order_by('category').annotate(sum=Sum('amount'))

    expense_form = ExpenseForm()  


    context = {
        'expense_form': expense_form,
        'expenses':expenses,
        'total_expenses':total_expenses,
        'yearly_sum':yearly_sum,
        'week_sum':week_sum,
        'monthly_sum':monthly_sum,
        'daily_sums':daily_sums ,
        'category_sums':category_sums,
        }

    return render(request, 'myapp/index.html', context)  # Corrected variable name in context dictionary


def edit(request,id):
    expense = Expense.objects.get(id=id)
    expense_form = ExpenseForm(instance=expense)
    if request.method == "POST":
        expense = Expense.objects.get(id=id)
        form = ExpenseForm(request.POST,instance=expense)
        if form.is_valid():
            form.save()
            return redirect('myapp:index')
    return render(request,'myapp/edit.html',{'expense_form': expense_form})


def delete(request,id):
    if request.method == "POST" and 'delete' in request.POST:
        expense = Expense.objects.get(id=id)
        expense.delete()
    return redirect('myapp:index')

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="{% static 'myapp/style.css' %}" rel="stylesheet">

</head>
<body>

    <nav class="shadow-lg">
        <div class="container flex flex-wrap justify-between items-center mx-auto">
            <a href="#" class="flex">
                <img class="h-12 m-4 "  src="{% static 'images/icon.png' %}" alt="Expense_traker">
                <span class="self-center text-bold">Expense Traker</span>
            </a>
        </div>
    </nav>

   {% block body %}

   {% endblock %}
</body>
</html>

myapp/templates/myapp/edit.html
{% extends 'myapp/base.html' %}
{% block body %}

<form action="" method="POST" class=" shadow-lg m-10 rounded-lg" >
    {% csrf_token %}
    <div class="form-container px-10 py-10 flex">
        <div class="mx-10">
            <div class="mb-5">
                <label>Expense Name</label>
            </div>
            <div class="border">
                {{expense_form.name }}
            </div>
        </div>

        <div class="mx-10">
            <div class="mb-5">
                <label>Amount</label>
            </div>
            <div class="border">
                {{expense_form.amount }}
            </div>
        </div>

        <div class="mx-10">
            <div class="mb-5">
                <label>Category</label>
            </div>
            <div class="border">
                {{expense_form.category }}
            </div>
        </div>

        <div class="mx-10 mt-8">
            <button class="bg-green-500 px-5 py-2 rounded-lg text-bold text-white">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% load humanize %}
{% block body %}
<div>
    <h2 class="m-10 font-bold ">Add Expense</h2>
</div>
    <form action="" method="POST" class=" shadow-lg m-10 rounded-lg" >
        {% csrf_token %}
        <div class="form-container px-10 py-10 flex">
            <div class="mx-10">
                <div class="mb-5">
                    <label>Expense Name</label>
                </div>
                <div class="border">
                    {{expense_form.name }}
                </div>
            </div>

            <div class="mx-10">
                <div class="mb-5">
                    <label>Amount</label>
                </div>
                <div class="border">
                    {{expense_form.amount }}
                </div>
            </div>

            <div class="mx-10">
                <div class="mb-5">
                    <label>Category</label>
                </div>
                <div class="border">
                    {{expense_form.category }}
                </div>
            </div>

            <div class="mx-10 mt-8">
                <button class="bg-green-500 px-5 py-2 rounded-lg text-bold text-white">Add</button>
            </div>
        </div>
    </form>

    <div>
        <h2 class="m-10 font-bold ">Expenses</h2>
    </div>
    <div class="shadow-lg m-10 rounded-lg">
        <div class="expense-header flex flex-wrap space-x-40 px-20 py-5">
            <span>Name</span>
            <span>Amount</span>
            <span>Category</span>
            <span>Date</span>
            <span>Edit</span>
            <span>Delete</span>
        </div>
    
        <hr class="m-2">
        {% for expense in expenses  %}
            <div class="expense-row flex flex-rap px-20 py-5">
                <span>{{expense.name}}</span>
                <span>${{expense.amount|intcomma}}</span>
                <span>{{expense.category}}</span>
                <span>{{expense.date}}</span>
                <span><a href="{% url 'myapp:edit' expense.id %}">
                    <img class="h-6" src="{% static 'images/edit.png' %}" alt="">
                </a></span>
                <span >
                    <form action="{% url 'myapp:delete' expense.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="delete">
                            <img class="h-6" src="{% static 'images/delete.png' %}" alt="">
                        </button>
                    </form>
                </span>
            </div>
        {% endfor %}

        <div class="flex">
            <span class="font-bold text-green-400">
                Total Expenses : 
            </span>
            <span class="font-bold text-green-400">
                ${{ total_expenses.total_amount }}
            </span>
        </div>

    </div>

    <div class="flex ">
        <div class="shadow-lg ml-15 px-20 py-5 rounded-lg">
            <h1 class="ml-5 font-bold text-gray-500">Last 365 days</h1>
            <h1 class="ml-5 font-bold text-green-500">
                ${{yearly_sum.total_amount|intcomma}}
            </h1>
        </div>
        <div class="shadow-lg ml-15 px-20 py-5 rounded-lg">
            <h1 class="ml-5 font-bold text-gray-500">Last 30 days</h1>
            <h1 class="ml-5 font-bold text-green-500">
                ${{monthly_sum.total_amount|intcomma}}
            </h1>
        </div>
        <div class="shadow-lg ml-15 px-20 py-5 rounded-lg">
            <h1 class="ml-5 font-bold text-gray-500">Last 7 days</h1>
            <h1 class="ml-5 font-bold text-green-500">
                ${{week_sum.total_amount|intcomma}}
            </h1>
        </div>
    </div>
    
    <div class="flex">
        <div class="w-1/2 shadow-lg m-10">
            <div class="flex flex-wrap space-x-40 font-bold px-20 py-5">
                <span>Past 30 days sum expense</span>
            </div>
            <div id="30-day-table">
                {% for daily_sum in daily_sums %}
                    <div class="flex flex-wrap px-20 py-5">
                        <span>  
                            {{daily_sum.date}}
                        </span>
                    </div>
                    <div class="flex flex-wrap px-20 text-green-500">
                        <span>  
                            ${{daily_sum.sum}}
                        </span>
                    </div>
                {%endfor%}
            </div>
        </div>

        <div class="w-1/2 shadow-lg m-10">
            <div class="flex flex-wrap space-x-40 font-bold px-20 py-5">
                <span>Category sum</span>
            </div>
            <div id="cat-sum-table">
                {% for category_sum in category_sums %}
                    <div class="flex flex-wrap px-20 py-5">
                        <span>  
                            {{category_sum.category}}
                        </span>
                    </div>
                    <div class="flex flex-wrap px-20 text-green-500">
                        <span>  
                            ${{category_sum.sum}}
                        </span>
                    </div>
                {%endfor%}
            </div>
        </div>
    </div>

    <div class="flex">
       
        <div class="w-1/2 shadow-lg ml-10">
            <h1 class="m-10">Daily Expense</h1>
            <canvas id="myChart1" class="m-10"></canvas>
        </div>

        <div class="w-1/2 shadow-lg ml-10">
            <h1 class="m-10">Expense spread across category</h1>
            <canvas id="myChart" class="m-10"></canvas>
        </div>

    </div>

    <!-- For any kinds of bar go an visit chartjs -->
    <!-- For any kinds of bar go an visit chartjs -->
    <!-- For any kinds of bar go an visit chartjs -->
    <!-- For any kinds of bar go an visit chartjs -->





    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.2/dist/chart.min.js"></script>

    <script>
        const cats = []
        const cats_sum = []
        const catSumDiv = document.getElementById('cat-sum-table').getElementsByTagName('div')
        for (var i = 0; i < catSumDiv.length; i++) {
           if(i%2 ==1){
                cats_sum.push(catSumDiv[i].innerText.replace("$",""))
            }else{
                cats.push(catSumDiv[i].innerText)
            }

        }
        // console.log(cats_sum);

        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: cats,
                datasets: [{
                    label: 'Expense across category',
                    data: cats_sum,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });

        const date = []
        const sums = []

        const dailySumDiv = document.getElementById('30-day-table').getElementsByTagName('div')
        for (var i = 0; i < dailySumDiv.length; i++) {
           if(i%2 ==1){
                sums.push(dailySumDiv[i].innerText.replace("$",""))
            }else{
                date.push(dailySumDiv[i].innerText)
            }

        }
        // console.log(date);
        // console.log(sums);

        var ctx1 = document.getElementById('myChart1').getContext('2d');
        var myChart1 = new Chart(ctx1, {
            type: 'line',
            data: {
                labels: date,
                datasets: [{
                    label: 'Expense Daily',
                    data: sums,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });


    </script>



<br><br>
{% endblock %}